PORTNAME?=	avidemux2
DISTVERSION=	2.8.2.g20260825
CATEGORIES=	multimedia
MASTER_SITES=	https://github.com/daeron767/avidemux2/releases/download/v2.8.2/:ffmpeg
DISTFILES=	${GH_PROJECT}-${DISTVERSION}-${GH_TAGNAME}_GH0.tar.gz \
		ffmpeg-7.0.2.tar.bz2:ffmpeg

MAINTAINER=	multimedia@FreeBSD.org
WWW=		https://avidemux.org/
LICENSE=	GPLv2

NOT_FOR_ARCHS=	powerpc powerpc64 powerpcspe
NOT_FOR_ARCHS_REASON=	CPU architecture not supported by upstream CMake script

BUILD_DEPENDS+=	bash:shells/bash \
		yasm:devel/yasm
LIB_DEPENDS+=	libmad.so:audio/libmad \
		libpng.so:graphics/png \
		libdrm.so:graphics/libdrm

USE_GITHUB=	nodefault
GH_ACCOUNT=	mean00
GH_PROJECT=	avidemux2
GH_TAGNAME=	13b4a26
WRKSRC=		${WRKDIR}/${PORTNAME}-${GH_TAGNAME}

USES+=		cmake compiler:c++17-lang localbase pkgconfig
USE_GNOME=	libxml2
USE_XORG+=	x11

CPPFLAGS+=	-I${LOCALBASE}/include
CXXFLAGS+=	-I${LOCALBASE}/include
LDFLAGS+=	-L${LOCALBASE}/lib -lexecinfo
CMAKE_ARGS+=	-DGNUMAKE_EXECUTABLE=gmake \
		-DAVIDEMUX_PACKAGER=none \
		-DGTK:BOOL=OFF \
		-DESD:BOOL=OFF \
		-DARTS:BOOL=OFF \
		-DALSA:BOOL=OFF \
		-DAFTEN:BOOL=OFF \
		-DCMAKE_DL_LIBS="" \
		-DLIBEXECINFO_INCLUDE_DIR=/usr/include \
		-DLIBEXECINFO_LIBRARY_DIR=/usr/lib \
		-DCMAKE_EXE_LINKER_FLAGS="${LDFLAGS}" \
		-DCMAKE_SHARED_LINKER_FLAGS="${LDFLAGS}" \
		-DCMAKE_PREFIX_PATH:PATH=${LOCALBASE}

MAKE_JOBS_UNSAFE=	yes

OPTIONS_DEFINE+=	AMR AOM ASS DCA FAAC FAAD FDK FONTCONFIG FREETYPE \
		JACK LAME NLS NVENC OPUS OSS PULSEAUDIO TINYPY TWOLAME VAAPI \
		VAPOURSYNTH VDPAU VORBIS VPX X264 X265 XVID
OPTIONS_DEFAULT=AMR AOM ASS DCA FAAC FAAD FDK FONTCONFIG FREETYPE LAME \
		NLS OPUS OSS TINYPY TWOLAME VORBIS VPX X264 X265 XVID
OPTIONS_EXCLUDE=VAPOURSYNTH
OPTIONS_SUB=	yes

AMR_DESC=	Opencore AMR codec support
AOM_DESC=	AOM AV1 decoder support
ASS_DESC=	SubStation Alpha (SSA/ASS) subtitle support
DCA_DESC=	DTS Coherent Acoustics decoding support
FAAC_DESC=	FAAC AAC audio encoding support
FAAD_DESC=	FAAD AAC audio decoding support
FDK_DESC=	Fraunhofer FDK AAC codec support
FONTCONFIG_DESC=	Fontconfig library support
FREETYPE_DESC=	FreeType font rendering support
JACK_DESC=	JACK audio server support
LAME_DESC=	LAME MP3 audio encoding support
NVENC_DESC=	NVIDIA NVENC/NVDEC support
OPUS_DESC=	Opus audio codec support
OSS_DESC=	Open Sound System audio support
PULSEAUDIO_DESC=	PulseAudio sound server support
TINYPY_DESC=	TinyPy Python scripting
TWOLAME_DESC=	TwoLAME MP2 audio encoding support
VAAPI_DESC=	VAAPI video acceleration support
VAPOURSYNTH_DESC=	VapourSynth support
VDPAU_DESC=		VDPAU video acceleration support
VORBIS_DESC=		Ogg Vorbis audio codec support
VPX_DESC=		VP8/VP9 video codec support
X264_DESC=		H.264 video encoding support via x264
X265_DESC=		HEVC video encoding support via x265
XVID_DESC=		MPEG-4 ASP video encoding support via Xvid

# Option Helpers
AMR_LIB_DEPENDS=	libopencore-amrnb.so:audio/opencore-amr \
			libopencore-amrwb.so:audio/opencore-amr
AMR_CMAKE_BOOL=		OPENCORE_AMR
AOM_LIB_DEPENDS=	libaom.so:multimedia/aom
AOM_CMAKE_OFF=		-DAOMDEC:BOOL=OFF
ASS_LIB_DEPENDS=	libass.so:multimedia/libass \
			libfribidi.so:converters/fribidi
ASS_CMAKE_BOOL=		LIBASS FRIBIDI
DCA_LIB_DEPENDS=	libdca.so:multimedia/libdca
DCA_CMAKE_OFF=		-DLIBDCA:BOOL=OFF
FAAC_LIB_DEPENDS=	libfaac.so:audio/faac
FAAC_CMAKE_BOOL=	FAAC
FAAD_LIB_DEPENDS=	libfaad.so:audio/faad
FAAD_CMAKE_BOOL=	FAAD NeAAC
FDK_LIB_DEPENDS=	libfdk-aac.so:audio/fdk-aac
FDK_CMAKE_BOOL=		FDK_AAC
FONTCONFIG_LIB_DEPENDS=	libfontconfig.so:x11-fonts/fontconfig
FONTCONFIG_CMAKE_BOOL=	FONTCONFIG
FREETYPE_LIB_DEPENDS=	libfreetype.so:print/freetype2
FREETYPE_CMAKE_BOOL=	FREETYPE2
JACK_LIB_DEPENDS=	libjack.so:audio/jack
JACK_CMAKE_BOOL=	JACK
LAME_LIB_DEPENDS=	libmp3lame.so:audio/lame
LAME_CMAKE_BOOL=	LAME
NLS_USES=		gettext-runtime
NLS_CMAKE_BOOL=		ENABLE_I18N
NVENC_BUILD_DEPENDS=	${LOCALBASE}/include/ffnvcodec/nvEncodeAPI.h:multimedia/ffnvcodec-headers
NVENC_CMAKE_BOOL=	NVENC
OPUS_LIB_DEPENDS=	libopus.so:audio/opus
OPUS_CMAKE_BOOL=	OPUS OPUS_ENCODER
OSS_CMAKE_BOOL=		ADM_SOUND_OSS
PULSEAUDIO_LIB_DEPENDS=	libpulse.so:audio/pulseaudio
PULSEAUDIO_CMAKE_BOOL=	PULSEAUDIOSIMPLE
TINYPY_CMAKE_BOOL=	ENABLE_TINYPY
TWOLAME_LIB_DEPENDS=	libtwolame.so:audio/twolame
TWOLAME_CMAKE_BOOL=	TWOLAME
VAAPI_LIB_DEPENDS=	libva.so:multimedia/libva \
			libva-drm.so:multimedia/libva \
			libva-x11.so:multimedia/libva
VAAPI_CMAKE_BOOL=	ENABLE_VAAPI VAAPI LIBVA
VAAPI_CMAKE_OFF=	-DFFMPEG_ENABLE_VAAPI:BOOL=OFF
VAPOURSYNTH_LIB_DEPENDS=libvapoursynth.so:multimedia/vapoursynth
VAPOURSYNTH_USE=	XORG=x11
VDPAU_LIB_DEPENDS=	libvdpau.so:multimedia/libvdpau
VDPAU_CMAKE_BOOL=	ENABLE_VDPAU VDPAU
VORBIS_LIB_DEPENDS=	libvorbis.so:audio/libvorbis
VORBIS_CMAKE_BOOL=	LIBVORBIS VORBIS
VPX_LIB_DEPENDS=	libvpx.so:multimedia/libvpx
VPX_CMAKE_BOOL=		VPXDEC VPXENC
X264_LIB_DEPENDS=	libx264.so:multimedia/libx264
X264_CMAKE_BOOL=	X264
X265_LIB_DEPENDS=	libx265.so:multimedia/x265
X265_CMAKE_BOOL=	X265
XVID_LIB_DEPENDS=	libxvidcore.so:multimedia/xvid
XVID_CMAKE_BOOL=	XVID
