--- avidemux_core/cmake/admInstallDir.cmake.orig	2026-08-25 22:30:39 UTC
+++ avidemux_core/cmake/admInstallDir.cmake
@@ -50,21 +50,24 @@ MACRO(ADM_INSTALL_LIB lib)
 # MACRO TO INSTALL REGULAR LIBS
 #
 MACRO(ADM_INSTALL_LIB lib)
-  INSTALL(TARGETS ${lib} RUNTIME
-    DESTINATION ${AVIDEMUX_BIN_DIR}    COMPONENT runtime
-    LIBRARY DESTINATION ${AVIDEMUX_LIB_DIR}  COMPONENT runtime
-    ARCHIVE DESTINATION ${AVIDEMUX_LIB_DIR}  COMPONENT dev
-  )
+  IF(NOT ADM_NO_CORE_INSTALL)
+    INSTALL(TARGETS ${lib} RUNTIME
+      DESTINATION ${AVIDEMUX_BIN_DIR}    COMPONENT runtime
+      LIBRARY DESTINATION ${AVIDEMUX_LIB_DIR}   COMPONENT runtime
+      ARCHIVE DESTINATION ${AVIDEMUX_LIB_DIR}   COMPONENT dev
+    )
+  ENDIF()
 ENDMACRO()
 
 MACRO(ADM_INSTALL_LIB_FILES files)
-  INSTALL(FILES ${files}
-      DESTINATION ${AVIDEMUX_LIB_DIR}
-      PERMISSIONS WORLD_READ WORLD_EXECUTE GROUP_READ GROUP_EXECUTE OWNER_WRITE OWNER_READ OWNER_EXECUTE
-      COMPONENT  runtime
-  )
+  IF(NOT ADM_NO_CORE_INSTALL)
+    INSTALL(FILES ${files}
+        DESTINATION ${AVIDEMUX_LIB_DIR}
+        PERMISSIONS WORLD_READ WORLD_EXECUTE GROUP_READ GROUP_EXECUTE OWNER_WRITE OWNER_READ OWNER_EXECUTE
+        COMPONENT   runtime
+    )
+  ENDIF()
 ENDMACRO()
-
 #
 # MACRO TO INSTALL REGULAR BIN
 #
@@ -79,54 +82,64 @@ MACRO(ADM_INSTALL_INCLUDE_FOLDER folder targetName)
 # Macro to install include folder
 #
 MACRO(ADM_INSTALL_INCLUDE_FOLDER folder targetName)
-  INSTALL(DIRECTORY ${folder}
-    DESTINATION ${AVIDEMUX_INSTALL_INCLUDE_DIR}/avidemux/${AVIDEMUX_MAJOR_MINOR}/${targetName}
-    COMPONENT dev
-    FILES_MATCHING PATTERN "*.h*"
-    PATTERN  "*.asm"
-  )
+  IF(NOT ADM_NO_CORE_INSTALL)
+    INSTALL(DIRECTORY ${folder}
+      DESTINATION ${AVIDEMUX_INSTALL_INCLUDE_DIR}/avidemux/${AVIDEMUX_MAJOR_MINOR}/${targetName}
+      COMPONENT dev
+      FILES_MATCHING PATTERN "*.h*"
+      PATTERN  "*.asm"
+    )
+  ENDIF()
 ENDMACRO()
 # #
 #
 # Macro to install include folder
 #
 MACRO(ADM_INSTALL_QT_INCLUDE_FOLDER folder targetName)
-  INSTALL(DIRECTORY ${folder}
-    DESTINATION ${AVIDEMUX_INSTALL_INCLUDE_DIR}/avidemux/${AVIDEMUX_MAJOR_MINOR}/${QT_EXTENSION}/${targetName}
-    COMPONENT dev
-    FILES_MATCHING PATTERN "*.h*"
-  )
+  IF(NOT ADM_NO_CORE_INSTALL)
+    INSTALL(DIRECTORY ${folder}
+      DESTINATION ${AVIDEMUX_INSTALL_INCLUDE_DIR}/avidemux/${AVIDEMUX_MAJOR_MINOR}/${QT_EXTENSION}/${targetName}
+      COMPONENT dev
+      FILES_MATCHING PATTERN "*.h*"
+    )
+  ENDIF()
 ENDMACRO()
 # #
 #
 # Macro to install cmake folder
 #
 MACRO(ADM_INSTALL_CMAKE_FOLDER folder)
-  INSTALL(DIRECTORY ${folder}
-    DESTINATION ${AVIDEMUX_INSTALL_INCLUDE_DIR}/avidemux/${AVIDEMUX_MAJOR_MINOR}/
-    COMPONENT dev
-    FILES_MATCHING PATTERN "*.cmake*"
-    PATTERN "attic" EXCLUDE
-  )
+  IF(NOT ADM_NO_CORE_INSTALL)
+    INSTALL(DIRECTORY ${folder}
+      DESTINATION ${AVIDEMUX_INSTALL_INCLUDE_DIR}/avidemux/${AVIDEMUX_MAJOR_MINOR}/
+      COMPONENT dev
+      FILES_MATCHING PATTERN "*.cmake*"
+      PATTERN "attic" EXCLUDE
+    )
+  ENDIF()
 ENDMACRO()
 #
 #
 # Macro to install cmake folder
 #
 MACRO(ADM_INSTALL_CMAKE_HELPER_FOLDER root foldername)
-  INSTALL(DIRECTORY ${root}/${foldername}
-    DESTINATION ${AVIDEMUX_INSTALL_INCLUDE_DIR}/avidemux/${AVIDEMUX_MAJOR_MINOR}/cmake/${foldername}
-    COMPONENT dev
-    FILES_MATCHING PATTERN "*.[cir]*"
-  )
+  IF(NOT ADM_NO_CORE_INSTALL)
+    INSTALL(DIRECTORY ${root}/${foldername}
+      DESTINATION ${AVIDEMUX_INSTALL_INCLUDE_DIR}/avidemux/${AVIDEMUX_MAJOR_MINOR}/cmake/${foldername}
+      COMPONENT dev
+      FILES_MATCHING PATTERN "*.[cir]*"
+    )
+  ENDIF()
 ENDMACRO()
 #
 # Macro to install include folder
 #
 MACRO(ADM_INSTALL_APP_HEADER folder)
-  INSTALL(FILE ${folder} ${ARGN}
-    DESTINATION ${AVIDEMUX_INSTALL_INCLUDE_DIR}/avidemux/${AVIDEMUX_MAJOR_MINOR}/ADM_app
-    COMPONENT dev
-  )
+  IF(NOT ADM_NO_CORE_INSTALL)
+    INSTALL(FILE ${folder} ${ARGN}
+      DESTINATION ${AVIDEMUX_INSTALL_INCLUDE_DIR}/avidemux/${AVIDEMUX_MAJOR_MINOR}/ADM_app
+      COMPONENT dev
+    )
+  ENDIF()
 ENDMACRO()
 #
